#!/bin/bash

echo "Chrome Web Store Deployment Guide"
echo "===================================="
echo ""
echo "To publish your extension to the Chrome Web Store:"
echo ""
echo "1️⃣ CREATE DEVELOPER ACCOUNT:"
echo "   • Go to: https://chrome.google.com/webstore/devconsole"
echo "   • Pay $5 one-time registration fee"
echo ""
echo "2️⃣ PREPARE EXTENSION PACKAGE:"
echo "   • Zip all extension files (excluding node_modules, scripts)"
echo "   • Maximum 100MB size limit"
echo ""
echo "3️⃣ REQUIRED ASSETS:"
echo "   • 128x128 icon ( already have: icon128.svg)"
echo "   • Screenshots (1280x800 or 640x400)"
echo "   • Store description and details"
echo ""
echo "4️⃣ UPLOAD & REVIEW:"
echo "   • Upload zip file"
echo "   • Fill out store listing details"
echo "   • Submit for review (1-3 days)"
echo ""
echo "💡 For now, local installation is perfect for personal use!"
echo ""
echo "📁 Extension folder: $(pwd)"
echo "🔗 Developer Console: https://chrome.google.com/webstore/devconsole"
